exclude: '^src/migrations'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:

    -   id: requirements-txt-fixer # проверяет файл requirements.txt
    -   id: trailing-whitespace  # убирает лишние пробелы
    -   id: check-added-large-files  # проверяет тяжелые файлы на изменения
    -   id: end-of-file-fixer  # добавляет пустую строку в конце файла
    -   id: check-yaml  # проверяет синтаксис .yaml файлов
    -   id: check-json  # проверяет синтаксис .json файлов
    -   id: check-case-conflict  # проверяет файлы, которые могут конфликтовать в файловых системах без учета регистра.
    -   id: check-merge-conflict  # проверяет файлы, содержащие конфликтные строки слияния.

# Форматирует код под PEP8 c помощью black
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        args: [--line-length=120]
        language_version: python3.11

# Отсортировывает импорты в проекте
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0  # версия 10 крашилась с поетри
    hooks:
      - id: isort
        exclude: __init__.py
        args: [ --profile, black, --filter-files ]

# Добавляет пропущенные запятые
#-   repo: https://github.com/asottile/add-trailing-comma
#    rev: v2.2.2
#    hooks:
#    -   id: add-trailing-comma
#        args: [--py36-plus]

# Сканер стилистических ошибок, нарушающие договоренности PEP8
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--ignore=E501", "--ignore=F821", "--max-line-length=120" ]
        exclude: src/migrations

# Форматирует docstring
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.6.0.rc1
    hooks:
    -   id: docformatter
        args: [--in-place]

# Форматирует код под PEP8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
    -   id: autopep8
        args: [--in-place, --max-line-length=120]

# Проверка статических типов с помощью mypy
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    -   id: mypy
        additional_dependencies: [pydantic>=1.10.4, types-redis>=4.4.0.4]

# Обновляет синтаксис Python кода в соответствии с последними версиями
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args: [--py311]
