version: '3.8'

services:
  test_app:
    container_name: test_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env.test"
    environment:
      CONFIG_FILE: ".env.test"
    entrypoint: >
      sh -c "
      alembic -c src/alembic.ini upgrade head &&
      pytest -vv -W ignore::DeprecationWarning
      "
    networks:
      - test_ylab
    depends_on:
      test_postgres:
        condition: service_healthy
      test_redis:
        condition: service_healthy

  test_redis:
    container_name: test_redis
    image: redis:latest
    expose:
      - 6379
    env_file:
      - ".env.test"
    environment:
      CONFIG_FILE: ".env.test"
    networks:
      - test_ylab
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      timeout: 20s
      retries: 10

  test_postgres:
    container_name: test_postgres
    image: postgres:15.1-alpine
    env_file:
      - ".env.test"
    environment:
      CONFIG_FILE: ".env.test"
    expose:
      - 5432
    networks:
      - test_ylab
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 20s
      retries: 100

networks:
  test_ylab:
    name: test_ylab
