titles = [
    "Tandoori Chicken Bites",
    "Spicy Tuna Roll Sushi",
    "Grilled Cheese Sandwich",
    "Pesto Pasta with Shrimp",
    "Pork Chops with Apples",
    "Roasted Veggie Quinoa Bowl",
    "Buffalo Cauliflower Bites",
    "Tomato Basil Soup",
    "Crispy Fish and Chips",
    "BBQ Pulled Pork Sandwich",
    "Lemon Garlic Shrimp Skewers",
    "Steak Fajitas with Peppers",
    "Creamy Tomato Alfredo Pasta",
    "Mushroom and Spinach Risotto",
    "Grilled Chicken Caesar Salad",
    "Crispy Onion Rings",
    "Spicy Beef and Broccoli",
    "Roasted Red Pepper Hummus",
    "Baked Sweet Potato Fries",
    "Shrimp Scampi Linguine",
    "Loaded Baked Potato Soup",
    "Grilled Pork Tenderloin",
    "Fried Rice with Vegetables",
    "Greek Salad with Grilled Chicken",
    "Crispy Fried Chicken Wings",
    "Tomato and Mozzarella Panini",
    "Shrimp Alfredo Pizza",
    "BBQ Ribs with Coleslaw",
    "Garlic Bread with Cheese",
]

descriptions = [
    "A classic sandwich with melted cheddar cheese on two slices of bread.",
    "Fettuccine with fresh basil pesto and juicy shrimp.",
    "Tender pork chops with caramelized apples and garlic mashed potatoes.",
    "Healthy bowl with roasted veggies and fluffy quinoa.",
    "Spicy and crispy roasted cauliflower with blue cheese dressing.",
    "Comforting bowl of creamy tomato soup with basil.",
    "Golden fish fillets and crispy french fries.",
    "Tender pulled pork with BBQ sauce and coleslaw on a toasted bun.",
    "Succulent shrimp marinated in lemon and garlic, grilled to perfection.",
    "Sizzling steak strips with bell peppers, onions, and warm tortillas.",
    "Fettuccine with creamy tomato alfredo sauce and parmesan cheese.",
    "Creamy arborio rice with mushrooms and spinach, finished with parmesan.",
    "Grilled chicken Caesar salad with croutons and dressing.",
    "Thinly sliced, crispy fried onion rings.",
    "Spicy stir-fried beef and broccoli with steamed rice.",
    "Smooth and creamy roasted red pepper hummus.",
    "Baked sweet potato fries with ketchup.",
    "Linguine with garlic, white wine, and lemon shrimp scampi sauce.",
    "Hearty soup with loaded baked potatoes, cheese, and bacon.",
    "Grilled pork tenderloin with rosemary roasted potatoes.",
    "Fried rice with mixed veggies and scrambled eggs.",
    "Classic Greek salad with romaine lettuce, feta, and grilled chicken.",
    "Crispy fried chicken wings seasoned with a blend of spices.",
    "Toasted panini with juicy tomatoes, mozzarella, and basil pesto.",
    "Alfredo pizza with juicy shrimp and parmesan cheese.",
    "Fall-off-the-bone BBQ ribs with creamy coleslaw on the side.",
    "Garlic bread with melted butter and parmesan cheese.",
    "Spicy chicken bites marinated in Indian spices and grilled.",
    "Spicy tuna and avocado sushi rolls with soy sauce.",
    "Healthy roasted veggie quinoa bowl.",
]
